include: vars.yaml

stages:
  - deploy

image: ghcr.io/akmalovaa/iac-tools

.ansible_prepare: &ansible_prepare
    - echo "$ANSIBLE_VAULT" > ansible/vault.key
    - echo "$SSH_PRIVATE_KEY" > ansible/ssh/id_rsa
    - echo "$SSH_PUBLIC_KEY" > ansible/ssh/id_rsa.pub
    - chmod -R 400 ./ansible/ssh


create-lxc:
  stage: deploy
  script:
    - *ansible_prepare
    - ansible-playbook ansible/lxc/lxc_create.yaml --extra-vars vmid=$VMID hostname=$NAME
  rules:
    - if: '$VMID && $NAME'
