include: vars.yaml

stages:
  - deploy

image: ghcr.io/akmalovaa/iac-tools

variables:
  ANSIBLE_CONFIG: "./ansible/ansible.cfg"
  VMID:
    value: ""
    description: VMID 100-255
  NAME:
    value: ""
    description: Container name

.ansible_prepare: &ansible_prepare
    - echo "$ANSIBLE_VAULT" > ansible/vault.key
    - echo "$SSH_PRIVATE_KEY" > ansible/ssh/id_rsa
    - echo "$SSH_PUBLIC_KEY" > ansible/ssh/id_rsa.pub
    - chmod -R 400 ./ansible/ssh

create-lxc:
  stage: deploy
  script:
    - *ansible_prepare
    - ansible-playbook ansible/playbook.yaml
  rules:
    - if: '$VMID && $NAME'
