name: Docker build ansible image

on:
  push:
    tags:
      - '*'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./ansible/Dockerfile --tag my-image-name:${GITHUB_REF#refs/*/}
