---
- name: Install aptitude
  tags: install
  apt:
    name: aptitude
    state: latest
    update_cache: true
  delegate_to: '{{ lxc_ip_address }}'

- name: Update cache & Full system update
  apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 432000
  delegate_to: '{{ lxc_ip_address }}'

- name: Install a list of packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates 
      - curl 
      - gnupg
  delegate_to: '{{ lxc_ip_address }}'

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  delegate_to: '{{ lxc_ip_address }}'

- name: Fetch delegated OS release name 
  shell: echo $(lsb_release -c -s)
  delegate_to: '{{ lxc_ip_address }}'
  register: code_name

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ code_name.stdout }} stable
    state: present
  delegate_to: '{{ lxc_ip_address }}'

- name: Debian-Based | Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
  delegate_to: '{{ lxc_ip_address }}'