---
- name: 'Create LXC Proxmox API'
  hosts: localhost
  vars:
    # LXC create settins
    vmid: "{{ lookup('env', 'VMID') | default(100) | int}}"
    hostname: "{{ lookup('env', 'NAME') | default('hostname') }}"
    # Proxmox settins
    proxmox_api_host: "{{ lookup('env', 'PROXMOX_API_HOST')}}"
    proxmox_api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
    proxmox_api_password: "{{ lookup('env', 'PROXMOX_API_PASSWORD')}}"
    proxmox_api_token_id: "{{ lookup('env', 'PROXMOX_API_TOKEN_ID') | default('id') }}"
    proxmox_api_token_secret: "{{ lookup('env', 'PROXMOX_API_TOKEN')}}"
    proxmox_node: "{{ lookup('env', 'PROXMOX_NODE')| default('pve1')}}"
    # LXC settings
    pve_lxc_user: root
    pve_lxc_root_password: "{{ lookup('env', 'LXC_PASSWORD') | default('12345') }}"
    pve_lxc_root_authorized_pubkey: "{{ lookup('file', 'ansible/ssh/id_rsa.pub') }}"
    pve_lxc_domain: "{{ lookup('env', 'DOMAIN_NAME') | default('example.com') }}"
    pve_lxc_disk: "{{ lookup('env', 'LXC_DISK') | default('local') }}" 
    pve_lxc_ostemplate: "{{ lookup('env', 'LXC_OS_TEMPLATE') | default('local:vztmpl/ubuntu-23.10-standard_23.10-1_amd64.tar.zs') }}"
    pve_lxc_network: "{{ lookup('env', 'LXC_NETWORK') | default('10.0.0.') }}" 
    pve_lxc_dns_server: "{{ lookup('env', 'LXC_DNS_SERVER') | default('10.0.0.1') }}"
    pve_lxc_gateway: "{{ lookup('env', 'LXC_GATEWAY') | default('10.0.0.1') }}"
    lxc_ip_address: '{{pve_lxc_network}}{{ vmid }}'
  tasks:
  - name: Create LXC minimal
    proxmox:
      api_user: '{{ proxmox_api_user }}'
      api_password: '{{ proxmox_api_password }}'
      api_host: '{{ proxmox_api_host }}'
      node: '{{ proxmox_node }}'
      vmid: '{{ vmid }}'
      hostname: '{{ hostname }}'
      password: '{{ pve_lxc_root_password }}'
      pubkey: '{{ pve_lxc_root_authorized_pubkey }}'
      ostemplate: '{{ pve_lxc_ostemplate }}'
      cores: 2
      disk: '{{pve_lxc_disk}}:10'
      unprivileged: true 
      netif: '{"net0":"name=eth0,ip={{ lxc_ip_address }}/24,gw={{ pve_lxc_gateway }},bridge=vmbr0,firewall=yes"}'
      nameserver: '{{ pve_lxc_dns_server }}'
      searchdomain: '{{ pve_lxc_domain }}'
      features: 
        - nesting=1
      onboot: true
      state: 'present'
      force: true
      timeout: 30
    register: result
    ignore_errors: true

  - name: Change LXC resources
    proxmox:
      api_user: '{{ proxmox_api_user }}'
      api_password: '{{ proxmox_api_password }}'
      api_host: '{{ proxmox_api_host }}'
      node: '{{ proxmox_node }}'
      vmid: '{{ vmid }}'
      hostname: '{{ hostname }}'
      cores: 4
      memory: 4096
      update: true
      tags:
        - ansible
  
  - name: Run lxc
    proxmox:
      vmid: '{{ vmid }}'
      api_user: '{{ proxmox_api_user }}'
      api_password: '{{ proxmox_api_password }}'
      api_host: '{{ proxmox_api_host }}'
      state: started
    register: result_run_lxc

  - name: Pause 10 seconds to runing container
    pause:
      seconds: 10
    when: result_run_lxc.changed

  - name: Add this lxc as host
    add_host:
      hostname: '{{ lxc_ip_address }}'
      ansible_ssh_user: 'root'
      ansible_ssh_private_key_file: 'ansible/ssh/id_rsa'

  - name: Prepare lxc - Install docker, docker compose
    include_tasks: /srv/ansible/lxc/install_docker.yaml
    # when: docker == "yes"

